language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g jspm
  - npm install -g surge
  - npm install -g firebase-tools
  - npm install
  - jspm install -y
  - npm run build
  - npm run compile
after_success:
  - npm run ci-deploy-to-surge
  - npm run ci-deploy-to-firebase

# only listen to changes in master
branches:
  only:
  - master
